# Generated by Django 4.2.16 on 2024-10-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_usuarios', '0002_usuario_delete_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epis',
            fields=[
                ('id_epi', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('quantidade', models.IntegerField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
