# Generated by Django 4.2.16 on 2024-10-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_usuarios', '0003_epis_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epis',
            name='quantidade',
            field=models.CharField(max_length=100),
        ),
    ]
